orbs:
  node: circleci/node@2.0.2
  heroku: circleci/heroku@x.y

version: 2.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
      - heroku/deploy-via-git:
        filters:
            branches:
              only:
                - master
          requires:
            - node/test
