version: 2.1

orbs:
  node: circleci/node@2.1.1
  slack: circleci/slack@3.4.2
  # heroku: circleci/heroku@1.0.1

jobs:
  build:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:13.11.0

    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
workflows:
  matrix-tests:
    jobs:
      - build
      - node/test:
          name: test1
          version: 13.11.0
          requires: 
            - build
      - node/test:
          name: test2
          version: 12.16.0
          requires: 
            - build
      - node/test:
          name: test3
          version: 10.19.0
          requires: 
            - build
      - approve_for_deploy:
          type: approval
          requires:
            - test1
            - test2
            - test3

      #  - deploy:
      #     name: netlifydeploy
      #     requires:
      #       - approve_for_deploy
      #     filters:
      #       branches:
      #         only: master
      # - heroku/deploy-via-git:
      #     requires:
      #       - approve_for_deploy
      #     filters:
      #       branches:
      #         only: master
      # - slack/approval-notification:
      #     message: Deployed!
      #     webhook: '${SLACK_WEBHOOK}'
      #     requires:
      #       - heroku/deploy-via-git
  # sched-wf:
  #   triggers:
  #     - schedule:
  #         cron: "* * * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
    
  #   jobs:
  #     - build
  #     - node/test:
  #         name: test1
  #         version: 13.11.0
  #         requires: 
  #           - build
  #     - node/test:
  #         name: test2
  #         version: 12.16.0
  #         requires: 
  #           - build
  #     - node/test:
  #         name: test3
  #         version: 10.19.0
  #         requires: 
  #           - build
  #     - approve_for_deploy:
  #         type: approval
  #         requires:
  #           - test1
  #           - test2
  #           - test3
  #     - heroku/deploy-via-git:
  #         requires:
  #           - approve_for_deploy
  #         filters:
  #           branches:
  #             only: master
  #     - slack/approval-notification:
  #         message: Deployed!
  #         webhook: '${SLACK_WEBHOOK}'
  #         requires:
  #           - heroku/deploy-via-git
      
