orbs:
  heroku: circleci/heroku@1.0.1
  node: circleci/node@2.0.2
  slack: circleci/slack@3.4.2
  

version: 2.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          name: test1
          version: 13.11.0
      - node/test:
          name: test2
          version: 12.16.0
      - node/test:
          name: test3
          version: 10.19.0
      - slack/approval-notification:
          name: approve
          message: Pending approval
          webhook: '${SLACK_WEBHOOK}'
      - heroku/deploy-via-git:
          type: approval
          requires:
            - approve
      