version: 2.1

orbs:
  node: circleci/node@2.0.2
  slack: circleci/slack@3.4.2
  heroku: circleci/heroku@1.0.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          name: test1
          version: 13.11.0
      - node/test:
          name: test2
          version: 12.16.0
      - node/test:
          name: test3
          version: 10.19.0
      - approve_for_testing:
          type: approval
          requires:
            - test1
            - test2
            - test3
      - slack/approval-notification:
          name: approve
          message: Pending approval
          webhook: '${SLACK_WEBHOOK}'
      - heroku/deploy-via-git:
          requires:
            - approve_for_testing
          filters:
            branches:
              only: master
      