version: 2.1

orbs:
  node: circleci/node@2.0.2
  slack: circleci/slack@3.4.2
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:13.11.0

    steps: 
      - checkout
      - run: npm install
workflows:
  matrix-tests:
    jobs:
      - build
      - node/test:
          name: test1
          version: 13.11.0
          requires: 
            - build
      - node/test:
          circleci_ip_ranges: true
          name: test2
          version: 12.16.0
          requires: 
            - build
      - node/test:
          circleci_ip_ranges: true
          name: test3
          version: 10.19.0
          requires: 
            - build
      - approve_for_deploy:
          circleci_ip_ranges: true
          type: approval
          requires:
            - test1
            - test2
            - test3
      - heroku/deploy-via-git:
          circleci_ip_ranges: true
          requires:
            - approve_for_deploy
          filters:
            branches:
              only: master
      - slack/approval-notification:
          circleci_ip_ranges: true
          message: Deployed!
          webhook: '${SLACK_WEBHOOK}'
          requires:
            - heroku/deploy-via-git
  # sched-wf:
  #   triggers:
  #     - schedule:
  #         cron: "* * * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
    
  #   jobs:
  #     - build
  #     - node/test:
  #         name: test1
  #         version: 13.11.0
  #         requires: 
  #           - build
  #     - node/test:
  #         name: test2
  #         version: 12.16.0
  #         requires: 
  #           - build
  #     - node/test:
  #         name: test3
  #         version: 10.19.0
  #         requires: 
  #           - build
  #     - approve_for_deploy:
  #         type: approval
  #         requires:
  #           - test1
  #           - test2
  #           - test3
  #     - heroku/deploy-via-git:
  #         requires:
  #           - approve_for_deploy
  #         filters:
  #           branches:
  #             only: master
  #     - slack/approval-notification:
  #         message: Deployed!
  #         webhook: '${SLACK_WEBHOOK}'
  #         requires:
  #           - heroku/deploy-via-git
      
