orbs:
  heroku: circleci/heroku@1.0.1
  node: circleci/node@2.0.2
  

version: 2.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          name: test1
          version: 13.11.0
      - node/test:
          name: test2
          version: 12.16.0
      - node/test:
          name: test3
          version: 10.19.0
      - heroku/deploy-via-git:
          requires:
            - test1
            - test2
            - test3